### PR TITLE
[FEATURE] Set button classNames

### PR DESCRIPTION
**Pull request by zzarcon**
This small PR add the ability to pass custom classNames to the button :dancer: 

A good showcase is this:

Let's say you are using `fastclick` in your site, and for some reasons you need a custom className to force the `click` event because it's not working properly on mobile...

``` javascript
    L.Control.Fullscreen.setButtonClass('needsclick');
```

Thanks for the lib and hope you like!

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Thanks for the contribution. This seems pretty niche though. How about doing something like `$('.leaflet-control-fullscreen-button').addClass('needsclick')` in your code after adding the control?

**Comment by zzarcon** [comment]
@jfirebaugh yeah this works as well, but accessing directly to the DOM and take care each time you remove or create the map it's not so nice, that's why it seems a bit fragile to me.

IMHO the control should offer a way to modify his properties (in this case just the `classNames`). Anyway, the proposal was how I thought that should work and it's opinionated and maybe doesn't fit with the goal of the lib or it's not the Leaflet way of doing things ^^

**Comment by jfirebaugh** [comment]
Yeah, for fixing issues that are specific to combining libraries A + B, it's usually better to go with a solution that works outside the libraries, rather than adding a feature to A specifically for B, or vice versa. Thanks for the suggestion though!

**Comment by zzarcon** [comment]
Yup that's true! Thanks for the feeback :dart:

**Pull request closed without merging**
